server:
  port: 8080
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: rivoj2024
#    keyStoreType: PKCS12
#    keyAlias: myapp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1}
    url: jdbc:postgresql://${DB_IP:localhost}:${DB_PORT:5432}/${DB_NAME:rivoj_storage}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none

do:
  spaces:
    key: DO008W9EHTX4EAW6U8KX
    secret: IMkZlDKxR9Ku+/ytLZy8V2yuB+SZX8bO23xOYgqwHa0
    endpoint2: https://rivojmediabucket.blr1.digitaloceanspaces.com
    endpoint: https://blr1.digitaloceanspaces.com
    region: blr1
    bucket: rivojmediabucket
