server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1}
    url: jdbc:postgresql://${DB_IP:localhost}:${DB_PORT:5433}/${DB_NAME:rivojstorage}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  mvc:
#    cors:
#      mappings:
#        "/**":
#          allowed-origins: "http://84.54.70.22:5173"
#          allowed-methods: "*"
#          allowed-headers: "*"
#          allow-credentials: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none

do:
  spaces:
    key: DO00X6PPB8UT7TTRXVW2
    secret: uyracnuBfeQr0euoLp6NWdnAu1kx+tV3Y/mOU+JkK/s
    endpoint2:  https://rivoj-bucket.blr1.digitaloceanspaces.com
    endpoint:  https://blr1.digitaloceanspaces.com
    region: blr1
    bucket: rivoj-bucket

jwt:
  expiry: 604800000
  secret: qwetuykyjhfdgsafgjhkoiutrefdsavzbxcnmktjyhretgwedfvbnjkrjyerhsfg

