server:
  port: 8080
  forward-headers-strategy: native
  ssl:
    key-store-type: PKCS12
    key-store: /app/keystore.p12
    key-store-password: 123456
    key-alias: 1
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1}
    url: jdbc:postgresql://${DB_IP:localhost}:5432/${DB_NAME:rivoj_education_db}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: rivoj-redis
      port: 6379
  main:
    allow-bean-definition-overriding: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
firebase:
  credentials:
    path: /app/fireBaseKeySDK.json
  secret: -----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDM1QkLQ0EGR7RP\nl8CARUAK9DSqlGi+x1muqLBg0JmzaGGQ1tibnX3iU2m+4ZIUPk7htJQgPvIcJV12\nOe6A2lhqAfqxzrMVk0vYV6Oc4UqyIws0OYALdvLeK6WoLuoSBN6R6ZSOYhVvBtw6\nNEJtFkRU5mS87t16g3/YQO26Wsk5Zb1s9TjO0MR4+I3RPi08PaylFV4hntmB1b/C\niFX/ZQS+z/JfSMKFDtyTkbpuWxn13voNehOsHCuk27eSWIabmlbAHyMt9YWLDgFO\nRs2Zaf16dV+0dP4y52x+NC7kvBnrv3N4B70NHtJ9mNwH8bGmdxnBvdwflslADRl5\n1KxZJF8BAgMBAAECggEAHeNI8EyGMK8mS4XaWC0ioOaMx8YjeZD3kFF7eQj/IGtO\n7zY2QZCrtWpT7/8UlGEaG/uAMKtWow49srpVx5X0mDVFOgwt2+xUAROao1HJVzBf\nWmW4fhPDcPEf+SgtTedJfbN+Un9T3tE6scB939KDsnqywNG+3flRnoGs3ogQPBBO\nPHRRy7rHW3vpY0DIGtBhfRtZe3q4Ta04aVpm9GNSIaDYpRXCVcvK0nIgbAZ+RFtI\naZBZH+M7ubdEGDLRe/WKWJ0743eDOSODoily40cEfDUBOt8D6l7+6MVEnj5jzO0N\nN7p9QmUQ7ZU7PEjl3+9CB0zijwe5+li1eWhcHioEJQKBgQDvfEF61ObEOSLX+Odo\nEWp+L9T2YBQpE3G7TiPU2ACZdKyIfucGzdRfkz0xoBVwBTBOONy1k0Qu/znJoJCs\nU8hXQzGT06tdA223y0ZRoF7xvNDokoUWIox45WImH0PD2ygs4dbj5iHcpv65y65b\nc/O1tTyxNhBoLmvKbcApOzX7tQKBgQDa9QfgDcabpTNxsj1sGxdHEuhaxuI9ygTY\ng/pguhuHcmbeN2bop8IlFJjNhYunfqNyeNhTG62xb8AXcJMyYbTuLvMuhK1B/cBg\ntCTKXULeaYlO7ufqHWiF/cEIAFu8xKq769FKh1VSO5pi31h5dx2robgcenyIujuQ\nwJri39+dnQKBgQC+kQux6HRxNF4Lqd7KKwGow/scyjuArB5WQ8mzduaTNgqM2x6P\nhX43R3zsXkxwxVA5DnpiantZQnMDhKda2ZiUB74NueOksjO+ixy7m3exuOQsDVul\nz3wkP7OoTjyoP15qyJMs6lWLtb8ArZli4JPPxhYzlafcnwPbIxZEOP+t+QKBgQC4\nBv3JeIqWwrCMPMyXEeXsnJ2hvkrkt+h+ud40cfc1ThfbaSEbJfRtCfSruDR6YFur\nmJnor/i6izwd90YgMDLLhbZqQKUGM+n+3SmW0++h033OU8mj4Xe6Nl6JBRQVgg4l\nx7uuMjSp2uKVezZ3UIAlgtSlSuVkXXI25UrIqHTfmQKBgGLdHE/7b9OD0VM4oJ6V\nz43aEUWUFeilPGtiB5qOKA6weIL8Hsi/qcpe+ntdBvPfCc+rrkPRyWR5B4FOW5BN\nsedYvx3UZ2wS7yKcsFa1Yt2/83MF0wJZ6DFIgiTd9d4tNip2nKBxXc7jCWkV/6tw\nXEngvhoevb8t8J5tBDK5gONh\n-----END PRIVATE KEY-----\n
do:
  spaces:
    key: DO00WUMDBQFHKBL2YY27
    secret: kvEXbi5+PakS0auDNar18BoOYH90yzXro6zT/PktzSo
    endpoint2: https://rivojspacesbucket.sfo3.digitaloceanspaces.com
    endpoint: https://sfo3.digitaloceanspaces.com
    region: sfo3
    bucket: rivojspacesbucket

jwt:
  expiry: 604800000
  secret: 94cd02ed0f443be13d85970ad39abeef32160c8935f1c6b6785a68e612630a73d4cb43dda05c446fa805f5393ef606bb0025c9753036b2036a754c03a2c44872e3b106ba4c523d7b99e1c21ed7f4c1d8598aaf709c14082aea8533f84caca9866e64287da29b799580e599c2c06bfb62fd6910acf952a6305878f7b9decc3cd86daf213ac02432a58b2bea20fbd7629856d4b37fcf19d9b9d68bcc8fa94cfff4424fe267b106502251d6095111a74fa2b3ac6a7275ffa449fc790e87f51e2a2fd14bece5082db9e086958eb3e84d4b8af3da7b2d4c4dad79bbdd28e95a4ec112a468197f9aece4be2459a525fd582f6819ac1909d4c6dc5d79
