server:
  port: 8080
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: rivoj2024
    keyStoreType: PKCS12
    keyAlias: myapp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1}
    url: jdbc:postgresql://${DB_IP:localhost}:${DB_PORT:5432}/${DB_NAME:rivoj_storage}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#  mvc:
#    cors:
#      mappings:
#        "/**":
#          allowed-origins: "http://84.54.70.22:5173"
#          allowed-methods: "*"
#          allowed-headers: "*"
#          allow-credentials: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none
