server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1}
    url: jdbc:postgresql://${DB_IP:localhost}:${DB_PORT:5433}/${DB_NAME:rivojstorage}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: 159.223.33.43
      port: 6379
      password: 1234

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none

do:
  spaces:
    key: DO0082YXEHNPKRRDJF2W
    secret: Es4wkTcPAnIiQ61m8XF7COc1WhAuyRhZRJMnAOxTkUM
    endpoint2: https://rivojspace1.sgp1.digitaloceanspaces.com
    endpoint: https://sgp1.digitaloceanspaces.com
    region: sgp1
    bucket: rivojspace1

jwt:
  expiry: 604800000
  secret: 94cd02ed0f443be13d85970ad39abeef32160c8935f1c6b6785a68e612630a73d4cb43dda05c446fa805f5393ef606bb0025c9753036b2036a754c03a2c44872e3b106ba4c523d7b99e1c21ed7f4c1d8598aaf709c14082aea8533f84caca9866e64287da29b799580e599c2c06bfb62fd6910acf952a6305878f7b9decc3cd86daf213ac02432a58b2bea20fbd7629856d4b37fcf19d9b9d68bcc8fa94cfff4424fe267b106502251d6095111a74fa2b3ac6a7275ffa449fc790e87f51e2a2fd14bece5082db9e086958eb3e84d4b8af3da7b2d4c4dad79bbdd28e95a4ec112a468197f9aece4be2459a525fd582f6819ac1909d4c6dc5d79
