server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1}
    url: jdbc:postgresql://${DB_IP:104.248.154.0}:${DB_PORT:5433}/${DB_NAME:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  mvc:
#    cors:
#      mappings:
#        "/**":
#          allowed-origins: "http://84.54.70.22:5173"
#          allowed-methods: "*"
#          allowed-headers: "*"
#          allow-credentials: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none
do:
  spaces:
    key: DO008W9EHTX4EAW6U8KX
    secret: IMkZlDKxR9Ku+/ytLZy8V2yuB+SZX8bO23xOYgqwHa0
    endpoint2: https://rivojmediabucket.blr1.digitaloceanspaces.com
    endpoint: https://blr1.digitaloceanspaces.com
    region: blr1
    bucket: rivojmediabucket