server:
  port: 8080
  forward-headers-strategy: native
  ssl:
    key-store-type: PKCS12
    key-store: /app/keystore.p12
    key-store-password: 123456
    key-alias: 1
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1}
    url: jdbc:postgresql://${DB_IP:localhost}:5432/${DB_NAME:rivoj_education_db}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: rivoj-redis
      port: 6379
  main:
    allow-bean-definition-overriding: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
firebase:
  credentials:
    path: /app/fireBaseKeySDK.json
do:
  spaces:
    key: DO00WUMDBQFHKBL2YY27
    secret: kvEXbi5+PakS0auDNar18BoOYH90yzXro6zT/PktzSo
    endpoint2: https://rivojspacesbucket.sfo3.digitaloceanspaces.com
    endpoint: https://sfo3.digitaloceanspaces.com
    region: sfo3
    bucket: rivojspacesbucket

jwt:
  expiry: 604800000
  secret: 94cd02ed0f443be13d85970ad39abeef32160c8935f1c6b6785a68e612630a73d4cb43dda05c446fa805f5393ef606bb0025c9753036b2036a754c03a2c44872e3b106ba4c523d7b99e1c21ed7f4c1d8598aaf709c14082aea8533f84caca9866e64287da29b799580e599c2c06bfb62fd6910acf952a6305878f7b9decc3cd86daf213ac02432a58b2bea20fbd7629856d4b37fcf19d9b9d68bcc8fa94cfff4424fe267b106502251d6095111a74fa2b3ac6a7275ffa449fc790e87f51e2a2fd14bece5082db9e086958eb3e84d4b8af3da7b2d4c4dad79bbdd28e95a4ec112a468197f9aece4be2459a525fd582f6819ac1909d4c6dc5d79
