server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: /app/keystore.p12
    key-store-password: 123456
    key-alias: myapp
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1}
    url: jdbc:postgresql://localhost:5432/rivojstorage

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: 159.223.33.43
      port: 6379
      password: 1234

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
firebase:
  credentials:
    path: /app/fireBaseKeySDK.json
  secret: -----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDr73quvGqPRy/4\nAZzaJ4s6iUWmaWnun01xvq6U+TL/agLhrtYNLB6wuUuetNkyy3CMhHS5eVz19TSN\nd1DMXRBG6lyQWnu9lFYe/8hDdc/+h5H2e/gyLjyl8skP3UgjEAjoi5QeeuHAtL92\n2rhI75LjmxM2d2zbMpZ86g6+yZLJimlyOUPMkaeVzJA7pG+HdmEKwAyvTeZMe38d\ncN4+BXkcKtRZ7Oor5veVc+ARhhXpKlUyxM+s9CBEi9cb+LMYCB/zulg3jpj+i7Gg\nDAepRwYs0HqH/7TQPPzhXIkBcmhFCkuGRPH9I4C/C/aiMxXhAd18jpu6wlFXlJ+Q\nUqwBou+HAgMBAAECggEAFdk+fjH6mDwaaBgWI2moDgqqRYfbhHqCHHdxCWCuZVK2\n45liPyQHz4vJQfAzcO3ABXM6r/ZaMni7niIffF1d5YNMgR2v+dVjyEkdjYm6cjKx\nxKakTFlVynRaRDrUtFKG0KokVFJC16qlVGday35MFwHEXLXggcgEgZrXNLnL+xfF\nuVHFXD85O/Hb0YWahzZK6hwPjHK87+QWa4GOnZMjN5IXd1dvudslztPT0edr3kWp\np21mZebyWJGEYoEwtp5Iq23EdyQcGW5VNp6QgDO7TGaP+WenP7WFkgWMTHhQp2Zw\n9SW6h8jUtMOJ8aXJo0dKK7NGjuHcLGUeUbnnDvSgCQKBgQD2x8DRkTuBP4GkEluH\n4qiNyyUY1jMCVzL3MQmY+wkngXQtNDo9d5zTnbnmKSZQ3cq/Cf3gzCstcgDig5tz\nBLoIM53EQYwda9PC0hlvRpOAvNOczVyT97pBGekLVstq7HWYPmgoWkwBLgKASAqv\nC0PrGMzi5zfxi0pknDr+eFwPxQKBgQD0wAEgx0U28xPislCfOcwBi/9GVXG54GcD\n3rzPRjOrdqKdeCrDQlIAHUiQl3Wr6slsWoHDP+POxxM/AKexC7ZlStQSgnM5U0JY\neKp1rhHnCkBs2j82+c024lulED3o+/0AEYu6bdizbMAe8a90f7yeyUTahdMM/ByP\nR/CrQ7DK2wKBgDhOQU9PjL0jqUevLJUngP/BLviovsC09prx5Fe0R1VtMv2xYexu\nYyjhXu4Fy4k94amO9Q8aZmubDFqiXpByrqN6a2/A6OA5nvpfh5AdEUCZVMr9DDdy\nmVuLNuHwbr85rmcLLiau25KVVdrBFTb1Igz8/ppy2Q/SkSm9f7RZ799lAoGBAMw8\n4XQZ9c9J/yEgzhhhIbV0vvxRVwrWkQBwwbxyB7Ig2MhxO7YfRNBln2VRjtd8oMMz\nr69gRFkMVSoxAL7EWFukmt4rT73ZlbbAUvbK4JOdQW/UnAXjZPVU5UcUC6W9ij2h\nZqmW+suXh6cK5fBgm+UhbbyxChJ+29JRJSu12/UbAoGAcjGxIZq0N9ft8fckHicS\nSt1Xvg0Z5xufZxFgBFMyTCHvLTHFLB/10ZgInwqJ/j2FcX3O37y/tCDdoVLtC6VN\n9xcFLrt715WZlRqrWDSGaJzDJKcNyYgYRJBRzzySFSZGDmrv9Lc5QXXUrWKOS4Xf\ncJNVdv3C5M2mlh7UXYH4fa0=\n-----END PRIVATE KEY-----\n
do:
  spaces:
    key: DO0082YXEHNPKRRDJF2W
    secret: Es4wkTcPAnIiQ61m8XF7COc1WhAuyRhZRJMnAOxTkUM
    endpoint2: https://rivojspace1.sgp1.digitaloceanspaces.com
    endpoint: https://sgp1.digitaloceanspaces.com
    region: sgp1
    bucket: rivojspace1

jwt:
  expiry: 604800000
  secret: 94cd02ed0f443be13d85970ad39abeef32160c8935f1c6b6785a68e612630a73d4cb43dda05c446fa805f5393ef606bb0025c9753036b2036a754c03a2c44872e3b106ba4c523d7b99e1c21ed7f4c1d8598aaf709c14082aea8533f84caca9866e64287da29b799580e599c2c06bfb62fd6910acf952a6305878f7b9decc3cd86daf213ac02432a58b2bea20fbd7629856d4b37fcf19d9b9d68bcc8fa94cfff4424fe267b106502251d6095111a74fa2b3ac6a7275ffa449fc790e87f51e2a2fd14bece5082db9e086958eb3e84d4b8af3da7b2d4c4dad79bbdd28e95a4ec112a468197f9aece4be2459a525fd582f6819ac1909d4c6dc5d79
